### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Promise

### ISSUE THREAD

**Issue by deweve** [joao-fontenele/express-prometheus-middleware#59]
Hi,

I'm using the middleware but when I call the endpoint I receive this exececption

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Promise

 at Function.byteLength (buffer.js:728:11)
    at chunkLength (/Users/etiennedewever/work/Polyconseil/coviflex/coviflex-api/node_modules/compression/index.js:245:14)
    at ServerResponse.end (/Users/etiennedewever/work/Polyconseil/coviflex/coviflex-api/node_modules/compression/index.js:100:20)

This is due because it sending a promise to res.end

It just need to be await first then send

**Comment by deweve** [comment]
I cannot push the modification  : 

The solution : 

Index.js line 157

```javascript
    res.set('Content-Type', Prometheus.register.contentType);
    const metrics = await Prometheus.register.metrics();
    return res.end(metrics);
```

**Comment by joao-fontenele** [comment]
hello @deweve, what version are you using? it seems to have an await already in the code in the following line

**Comment by deweve** [comment]
It seems I'm using the 1.0 version. I've just realised the await in the return. I can check if the problem persists
